'use strict';
const { app } = require('@azure/functions');
const { TableClient } = require('@azure/data-tables');
const connectionString=()=>process.env.VOLLEYBALL_STORAGE_CONNECTION;
const tc=n=>TableClient.fromConnectionString(connectionString(),n);
const res=(status,body)=>({status,jsonBody:body});
const clean=(v,n=150)=>String(v||'').trim().slice(0,n);
async function ensure(c){try{await c.createTable()}catch(e){if(e.statusCode!==409)throw e}}
function principal(req){const h=req.headers.get('x-ms-client-principal');if(!h)return null;try{return JSON.parse(Buffer.from(h,'base64').toString('utf8'))}catch{return null}}
async function member(teamId,userId){const c=tc('VTMTeamMembers');await ensure(c);try{return await c.getEntity(teamId,userId)}catch(e){if(e.statusCode===404)return null;throw e}}
async function allowed(teamId,p,write=false){const m=p&&await member(teamId,p.userId);return m&&(!write||['Owner','Coach'].includes(m.role))?m:null}
async function list(c,filter){const a=[];for await(const x of c.listEntities({queryOptions:{filter}}))a.push(x);return a}
app.http('attendance',{methods:['GET','POST'],authLevel:'anonymous',route:'attendance',handler:async req=>{try{const p=principal(req);if(!p)return res(401,{error:'Niet ingelogd'});if(req.method==='GET'){const teamId=req.query.get('teamId'),matchId=req.query.get('matchId');if(!await allowed(teamId,p))return res(403,{error:'Geen toegang'});const pc=tc('VTMPlayers'),ac=tc('VTMAttendance');await ensure(pc);await ensure(ac);const players=await list(pc,`PartitionKey eq '${teamId}'`),records=await list(ac,`PartitionKey eq '${matchId}'`),byId=new Map(records.map(x=>[x.playerId,x]));return res(200,players.filter(x=>x.active!==false).map(x=>{const a=byId.get(x.playerId);return{playerId:x.playerId,name:x.name,number:x.number||'',role:x.role||'',status:a?.status||'Unknown',note:a?.note||'',updatedAt:a?.updatedAt||''}}))}
const b=await req.json(),teamId=clean(b.teamId,100),matchId=clean(b.matchId,100);if(!await allowed(teamId,p,true))return res(403,{error:'Geen schrijfrechten'});if(!teamId||!matchId||!Array.isArray(b.players))return res(400,{error:'Ongeldige aanwezigheidsgegevens'});const ac=tc('VTMAttendance'),pc=tc('VTMPlayers');await ensure(ac);await ensure(pc);const valid=new Set(['Present','Absent']);for(const item of b.players){const playerId=clean(item.playerId,100),status=clean(item.status,20);if(!playerId||!valid.has(status))return res(400,{error:'Iedere speler moet aanwezig of afwezig zijn'});let player;try{player=await pc.getEntity(teamId,playerId)}catch(e){if(e.statusCode===404)return res(400,{error:'Speler niet gevonden'});throw e}await ac.upsertEntity({partitionKey:matchId,rowKey:playerId,teamId,matchId,playerId,playerName:clean(player.name),playerNumber:clean(player.number,10),status,note:clean(item.note,200),updatedAt:new Date().toISOString(),updatedBy:p.userId},'Replace')}return res(200,{ok:true})}catch(e){console.error('attendance failed',e);return res(500,{error:`Aanwezigheid opslaan mislukt: ${e.message||'onbekende fout'}`})}}});
app.http('attendanceStats',{methods:['GET'],authLevel:'anonymous',route:'attendance/stats',handler:async req=>{try{const p=principal(req),teamId=req.query.get('teamId');if(!p||!await allowed(teamId,p))return res(403,{error:'Geen toegang'});const pc=tc('VTMPlayers'),ac=tc('VTMAttendance'),sc=tc('VTMSets'),lc=tc('VTMLineups'),xc=tc('VTMSubstitutions');for(const c of [pc,ac,sc,lc,xc])await ensure(c);const players=await list(pc,`PartitionKey eq '${teamId}'`),att=await list(ac,`teamId eq '${teamId}'`),sets=await list(sc,`PartitionKey eq '${teamId}'`),lineups=await list(lc,`PartitionKey eq '${teamId}'`),subs=await list(xc,`teamId eq '${teamId}'`),roles=['setter','buiten1','midden1','dia','buiten2','midden2'];const attMap=new Map(att.map(x=>[`${x.matchId}|${x.playerId}`,x.status])),appear=new Map();for(const l of lineups){const key=`${l.matchId}|${Number(l.setNumber)}`;if(!appear.has(key))appear.set(key,new Set());for(const r of roles){const id=l[`${r}Id`];if(id)appear.get(key).add(id)}}for(const x of subs){const key=`${x.matchId}|${Number(x.setNumber)}`;if(!appear.has(key))appear.set(key,new Set());if(x.outPlayerId)appear.get(key).add(x.outPlayerId);if(x.inPlayerId)appear.get(key).add(x.inPlayerId)}const stats=players.map(pl=>{let matchesPresent=0,matchesAbsent=0,setsPlayed=0,setsBench=0;for(const a of att.filter(x=>x.playerId===pl.playerId)){if(a.status==='Present')matchesPresent++;if(a.status==='Absent')matchesAbsent++}for(const set of sets){if(attMap.get(`${set.matchId}|${pl.playerId}`)!=='Present')continue;const played=appear.get(`${set.matchId}|${Number(set.setNumber)}`)?.has(pl.playerId);if(played)setsPlayed++;else setsBench++}return{playerId:pl.playerId,name:pl.name,number:pl.number||'',matchesPresent,matchesAbsent,setsPlayed,setsBench}});return res(200,stats)}catch(e){console.error('attendance stats failed',e);return res(500,{error:`Statistieken laden mislukt: ${e.message||'onbekende fout'}`})}}});
