'use strict';
const { app } = require('@azure/functions');
const { TableClient } = require('@azure/data-tables');
const crypto = require('crypto');
const connectionString = () => process.env.VOLLEYBALL_STORAGE_CONNECTION;
const tableClient = name => TableClient.fromConnectionString(connectionString(), name);
const response = (status, body) => ({ status, jsonBody: body });
const clean = (value, n=150) => String(value || '').trim().slice(0,n);
const ROLES = ['setter','buiten1','midden1','dia','buiten2','midden2'];
async function ensureTable(c){try{await c.createTable()}catch(e){if(e.statusCode!==409)throw e}}
function principal(req){const h=req.headers.get('x-ms-client-principal');if(!h)return null;try{return JSON.parse(Buffer.from(h,'base64').toString('utf8'))}catch{return null}}
async function membership(teamId,userId){const c=tableClient('VTMTeamMembers');await ensureTable(c);try{return await c.getEntity(teamId,userId)}catch(e){if(e.statusCode===404)return null;throw e}}
async function authorize(teamId,p,write=false){const m=p&&await membership(teamId,p.userId);return m&&(!write||['Owner','Coach'].includes(m.role))?m:null}
const lineupKey=(matchId,setNumber)=>`${matchId}_${String(setNumber).padStart(2,'0')}`;
async function readPlayer(c,teamId,id){try{return await c.getEntity(teamId,id)}catch(e){if(e.statusCode===404)return null;throw e}}
async function listHistory(matchId,setNumber){const c=tableClient('VTMSubstitutions');await ensureTable(c);const a=[];for await(const x of c.listEntities({queryOptions:{filter:`PartitionKey eq '${matchId}' and setNumber eq ${Number(setNumber)}`}}))a.push(x);a.sort((x,y)=>String(x.createdAt).localeCompare(String(y.createdAt)));return{client:c,items:a}}
function publicItem(x){return{substitutionId:x.substitutionId,setNumber:Number(x.setNumber),role:x.role,outPlayerId:x.outPlayerId,outPlayerName:x.outPlayerName,outPlayerNumber:x.outPlayerNumber||'',inPlayerId:x.inPlayerId,inPlayerName:x.inPlayerName,inPlayerNumber:x.inPlayerNumber||'',teamScore:Number(x.teamScore||0),opponentScore:Number(x.opponentScore||0),rotation:Number(x.rotation||0),serving:x.serving||'',createdAt:x.createdAt}}
app.http('substitutions',{methods:['GET','POST'],authLevel:'anonymous',route:'substitutions',handler:async req=>{try{const p=principal(req);if(!p)return response(401,{error:'Niet ingelogd'});if(req.method==='GET'){const teamId=req.query.get('teamId'),matchId=req.query.get('matchId'),setNumber=Number(req.query.get('setNumber'));if(!await authorize(teamId,p))return response(403,{error:'Geen toegang'});return response(200,(await listHistory(matchId,setNumber)).items.map(publicItem))}
const b=await req.json(),teamId=clean(b.teamId,100),matchId=clean(b.matchId,100),setNumber=Number(b.setNumber),role=clean(b.role,20),inPlayerId=clean(b.inPlayerId,100);if(!await authorize(teamId,p,true))return response(403,{error:'Geen schrijfrechten'});if(!teamId||!matchId||!Number.isInteger(setNumber)||!ROLES.includes(role)||!inPlayerId)return response(400,{error:'Ongeldige wisselgegevens'});
const lc=tableClient('VTMLineups');await ensureTable(lc);let lineup;try{lineup=await lc.getEntity(teamId,lineupKey(matchId,setNumber))}catch(e){if(e.statusCode===404)return response(404,{error:'Opstelling niet gevonden'});throw e}
const outPlayerId=clean(lineup[`${role}Id`],100);if(!outPlayerId)return response(409,{error:'Op deze rol staat geen speler'});if(outPlayerId===inPlayerId)return response(400,{error:'Kies een andere speler'});for(const r of ROLES)if(clean(lineup[`${r}Id`],100)===inPlayerId)return response(409,{error:'Deze speler staat al in het veld'});
const pc=tableClient('VTMPlayers');await ensureTable(pc);const incoming=await readPlayer(pc,teamId,inPlayerId),outgoing=await readPlayer(pc,teamId,outPlayerId);if(!incoming)return response(400,{error:'Inkomende speler niet gevonden'});const ac=tableClient('VTMAttendance');await ensureTable(ac);try{const ar=await ac.getEntity(matchId,inPlayerId);if(ar.status!=='Present')return response(409,{error:'De inkomende speler staat niet als aanwezig geregistreerd'})}catch(e){if(e.statusCode===404)return response(409,{error:'Leg eerst de aanwezigheid voor deze wedstrijd vast'});throw e}const sets=tableClient('VTMSets');await ensureTable(sets);let setEntity;try{setEntity=await sets.getEntity(teamId,`${matchId}_${String(setNumber).padStart(2,'0')}`)}catch(e){if(e.statusCode!==404)throw e;setEntity={teamScore:0,opponentScore:0}}
const id=`${Date.now()}_${crypto.randomUUID()}`,now=new Date().toISOString(),sc=tableClient('VTMSubstitutions');await ensureTable(sc);await sc.createEntity({partitionKey:matchId,rowKey:id,substitutionId:id,teamId,matchId,setNumber,role,outPlayerId,outPlayerName:clean(lineup[`${role}Name`]||outgoing?.name),outPlayerNumber:clean(lineup[`${role}Number`]||outgoing?.number,10),inPlayerId,inPlayerName:clean(incoming.name),inPlayerNumber:clean(incoming.number,10),teamScore:Number(setEntity.teamScore||0),opponentScore:Number(setEntity.opponentScore||0),rotation:Number(lineup.rotation||0),serving:lineup.serving||'',createdAt:now,createdBy:p.userId});
lineup[`${role}Id`]=inPlayerId;lineup[`${role}Name`]=clean(incoming.name);lineup[`${role}Number`]=clean(incoming.number,10);lineup.updatedAt=now;lineup.updatedBy=p.userId;await lc.updateEntity(lineup,'Replace');return response(201,{ok:true,substitution:publicItem(await sc.getEntity(matchId,id))})}catch(e){console.error('substitutions failed',e);return response(500,{error:`Wissel mislukt: ${e.message||'onbekende fout'}`})}}});
app.http('substitutionUndo',{methods:['POST'],authLevel:'anonymous',route:'substitutions/undo',handler:async req=>{try{const p=principal(req);if(!p)return response(401,{error:'Niet ingelogd'});const b=await req.json(),teamId=clean(b.teamId,100),matchId=clean(b.matchId,100),setNumber=Number(b.setNumber);if(!await authorize(teamId,p,true))return response(403,{error:'Geen schrijfrechten'});const history=await listHistory(matchId,setNumber),last=history.items.at(-1);if(!last)return response(409,{error:'Geen wissel om ongedaan te maken'});const lc=tableClient('VTMLineups');await ensureTable(lc);const lineup=await lc.getEntity(teamId,lineupKey(matchId,setNumber));if(clean(lineup[`${last.role}Id`],100)!==clean(last.inPlayerId,100))return response(409,{error:'De laatste wissel kan niet veilig worden hersteld'});lineup[`${last.role}Id`]=last.outPlayerId;lineup[`${last.role}Name`]=last.outPlayerName;lineup[`${last.role}Number`]=last.outPlayerNumber||'';lineup.updatedAt=new Date().toISOString();lineup.updatedBy=p.userId;await lc.updateEntity(lineup,'Replace');await history.client.deleteEntity(matchId,last.rowKey);return response(200,{ok:true})}catch(e){console.error('substitution undo failed',e);return response(500,{error:`Wissel terugdraaien mislukt: ${e.message||'onbekende fout'}`})}}});
