'use strict';
const { app } = require('@azure/functions');
const { TableClient } = require('@azure/data-tables');
const crypto = require('crypto');
const connectionString=()=>process.env.VOLLEYBALL_STORAGE_CONNECTION;
const table=n=>TableClient.fromConnectionString(connectionString(),n);
const response=(status,body)=>({status,jsonBody:body});
const clean=(v,n=150)=>String(v||'').trim().slice(0,n);
async function ensure(c){try{await c.createTable()}catch(e){if(e.statusCode!==409)throw e}}
function principal(req){const h=req.headers.get('x-ms-client-principal');if(!h)return null;try{return JSON.parse(Buffer.from(h,'base64').toString('utf8'))}catch{return null}}
async function membership(teamId,userId){const c=table('VTMTeamMembers');await ensure(c);try{return await c.getEntity(teamId,userId)}catch(e){if(e.statusCode===404)return null;throw e}}
async function authorize(teamId,p,roles){const m=p&&await membership(teamId,p.userId);return m&&(!roles||roles.includes(m.role))?m:null}
async function del(c,pk,rk){try{await c.deleteEntity(pk,rk)}catch(e){if(e.statusCode!==404)throw e}}
async function delFilter(name,filter){const c=table(name);await ensure(c);const rows=[];for await(const x of c.listEntities({queryOptions:{filter}}))rows.push([x.partitionKey,x.rowKey]);for(const [pk,rk] of rows)await del(c,pk,rk);return rows.length}
async function delMatch(teamId,matchId){for(const t of ['VTMPoints','VTMRotations','VTMSubstitutions'])await delFilter(t,`PartitionKey eq '${matchId}'`);await delFilter('VTMAttendance',`teamId eq '${teamId}' and matchId eq '${matchId}'`);for(const t of ['VTMSets','VTMLineups'])await delFilter(t,`PartitionKey eq '${teamId}' and matchId eq '${matchId}'`);const c=table('VTMMatches');await ensure(c);await del(c,teamId,matchId)}
app.http('removePlayer',{methods:['POST'],authLevel:'anonymous',route:'admin/remove/player',handler:async req=>{try{const p=principal(req),b=await req.json(),teamId=clean(b.teamId,100),playerId=clean(b.playerId,100);if(!p)return response(401,{error:'Niet ingelogd'});if(!teamId||!playerId)return response(400,{error:'TeamId of speler-id ontbreekt'});if(!await authorize(teamId,p,['Owner','Coach']))return response(403,{error:'Geen schrijfrechten'});const c=table('VTMPlayers');await ensure(c);await del(c,teamId,playerId);await delFilter('VTMAttendance',`teamId eq '${teamId}' and playerId eq '${playerId}'`);return response(200,{ok:true})}catch(e){console.error('remove player',e);return response(500,{error:`Speler verwijderen mislukt: ${e.message||'onbekende fout'}`})}}});
app.http('removeMatch',{methods:['POST'],authLevel:'anonymous',route:'admin/remove/match',handler:async req=>{try{const p=principal(req),b=await req.json(),teamId=clean(b.teamId,100),matchId=clean(b.matchId,100);if(!p)return response(401,{error:'Niet ingelogd'});if(!teamId||!matchId)return response(400,{error:'TeamId of wedstrijd-id ontbreekt'});if(!await authorize(teamId,p,['Owner','Coach']))return response(403,{error:'Geen schrijfrechten'});await delMatch(teamId,matchId);return response(200,{ok:true})}catch(e){console.error('remove match',e);return response(500,{error:`Wedstrijd verwijderen mislukt: ${e.message||'onbekende fout'}`})}}});
app.http('removeMember',{methods:['POST'],authLevel:'anonymous',route:'admin/remove/member',handler:async req=>{try{const p=principal(req),b=await req.json(),teamId=clean(b.teamId,100),memberId=clean(b.memberId,200);if(!p)return response(401,{error:'Niet ingelogd'});if(!teamId||!memberId)return response(400,{error:'TeamId of teamlid-id ontbreekt'});if(!await authorize(teamId,p,['Owner']))return response(403,{error:'Alleen de eigenaar mag teamleden verwijderen'});const target=await membership(teamId,memberId);if(!target)return response(404,{error:'Teamlid niet gevonden'});if(target.role==='Owner')return response(409,{error:'De eigenaar kan niet worden verwijderd'});const c=table('VTMTeamMembers');await ensure(c);await del(c,teamId,memberId);const email=clean(target.email).toLowerCase();if(email){const i=table('VTMInvitations');await ensure(i);await del(i,teamId,crypto.createHash('sha256').update(email).digest('hex'))}return response(200,{ok:true})}catch(e){console.error('remove member',e);return response(500,{error:`Teamlid verwijderen mislukt: ${e.message||'onbekende fout'}`})}}});
app.http('removeTeam',{methods:['POST'],authLevel:'anonymous',route:'admin/remove/team',handler:async req=>{try{const p=principal(req),b=await req.json(),teamId=clean(b.teamId,100);if(!p)return response(401,{error:'Niet ingelogd'});if(!teamId)return response(400,{error:'TeamId ontbreekt'});if(!await authorize(teamId,p,['Owner']))return response(403,{error:'Alleen de eigenaar mag het team verwijderen'});const matches=table('VTMMatches');await ensure(matches);const ids=[];for await(const x of matches.listEntities({queryOptions:{filter:`PartitionKey eq '${teamId}'`}}))ids.push(x.matchId||x.rowKey);for(const id of ids)await delMatch(teamId,id);for(const t of ['VTMPlayers','VTMTeamMembers','VTMInvitations','VTMSets','VTMLineups'])await delFilter(t,`PartitionKey eq '${teamId}'`);const teams=table('VTMTeams');await ensure(teams);await del(teams,'team',teamId);return response(200,{ok:true})}catch(e){console.error('remove team',e);return response(500,{error:`Team verwijderen mislukt: ${e.message||'onbekende fout'}`})}}});
